// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVIEihmAvzHeIFY_w401n01K0_WyS0F8k',
    appId: '1:124649287252:web:302cdd0906eb6bbdd007c1',
    messagingSenderId: '124649287252',
    projectId: 'dj-link-1188a',
    authDomain: 'dj-link-1188a.firebaseapp.com',
    storageBucket: 'dj-link-1188a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeE8x2JdwOR0hEv6fenzecPDHEehilc8M',
    appId: '1:124649287252:android:08dc4b847bfa0f4fd007c1',
    messagingSenderId: '124649287252',
    projectId: 'dj-link-1188a',
    storageBucket: 'dj-link-1188a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfTwQcL-wBbGKwqwUmaWSK1ODn1mJsJf8',
    appId: '1:124649287252:ios:407b7da4c71096c9d007c1',
    messagingSenderId: '124649287252',
    projectId: 'dj-link-1188a',
    storageBucket: 'dj-link-1188a.firebasestorage.app',
    iosBundleId: 'com.islemtires.djLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfTwQcL-wBbGKwqwUmaWSK1ODn1mJsJf8',
    appId: '1:124649287252:ios:2f9bf0119fb826b4d007c1',
    messagingSenderId: '124649287252',
    projectId: 'dj-link-1188a',
    storageBucket: 'dj-link-1188a.firebasestorage.app',
    iosBundleId: 'com.example.djLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVIEihmAvzHeIFY_w401n01K0_WyS0F8k',
    appId: '1:124649287252:web:a0ecb69ea473b2e8d007c1',
    messagingSenderId: '124649287252',
    projectId: 'dj-link-1188a',
    authDomain: 'dj-link-1188a.firebaseapp.com',
    storageBucket: 'dj-link-1188a.firebasestorage.app',
  );
}
